#!/bin/bash

#enumerate files
a=1
for i in *.JPG; do
  new=$(printf "$a.JPG")
  mv -- "$i" "$new"
  let a=a+1
done

a=1
for i in *.JPG; do
  new=$(printf "$a.JPG")
  mv -- "$i" "$new"
  let a=a+1
done

a=1
for i in *.png; do
  new=$(printf "$a.png")
  mv -- "$i" "$new"
  let a=a+1
done

#delete .png files
#a=1
#for i in *.PNG; do
#  rm $i
#  let a=a+1
#done



